repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --remove-all-notebook-metadata
          - --  # end-of-options; pre-commit appends file paths after this
